{
  "date": "2025-08-23",
  "created_at": "2025-08-23T01:30:57.878693",
  "error_count": 264,
  "errors": [
    {
      "timestamp": "2025-08-23T15:51:57.202414",
      "service": "image_generator",
      "logger": "image_generator",
      "level": "ERROR",
      "message": "Devotional mode: display_text set to '03:51 PM - Saturday, August 23, 2025'",
      "function": "_add_verse_reference_display",
      "line": 1956,
      "filename": "image_generator.py"
    },
    {
      "timestamp": "2025-08-23T15:52:00.925439",
      "service": "image_generator",
      "logger": "image_generator",
      "level": "ERROR",
      "message": "_add_verse_reference_display: is_devotional=True, has_devotional_text=True",
      "function": "_add_verse_reference_display",
      "line": 1947,
      "filename": "image_generator.py"
    },
    {
      "timestamp": "2025-08-23T15:52:00.937034",
      "service": "image_generator",
      "logger": "image_generator",
      "level": "ERROR",
      "message": "Devotional mode: display_text set to '03:52 PM - Saturday, August 23, 2025'",
      "function": "_add_verse_reference_display",
      "line": 1956,
      "filename": "image_generator.py"
    },
    {
      "timestamp": "2025-08-23T15:52:01.575241",
      "service": "image_generator",
      "logger": "image_generator",
      "level": "ERROR",
      "message": "_add_verse_reference_display: is_devotional=True, has_devotional_text=True",
      "function": "_add_verse_reference_display",
      "line": 1947,
      "filename": "image_generator.py"
    },
    {
      "timestamp": "2025-08-23T15:52:01.587880",
      "service": "image_generator",
      "logger": "image_generator",
      "level": "ERROR",
      "message": "Devotional mode: display_text set to '03:52 PM - Saturday, August 23, 2025'",
      "function": "_add_verse_reference_display",
      "line": 1956,
      "filename": "image_generator.py"
    },
    {
      "timestamp": "2025-08-23T17:25:44.054174",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:26:11.221592",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:27:06.812898",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:28:08.679041",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:29:10.054245",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:30:06.975409",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:31:06.223487",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:32:07.710744",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:33:07.222854",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:34:07.467186",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T17:35:06.886418",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T19:49:25.714799",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.11 - - [23/Aug/2025 19:49:25] code 400, message Bad request version ('\\x94\u00db\\x00*JJ\\x13\\x02\\x13\\x03\\x13\\x01\u00c0,\u00c0+\u00cc\u00a9\u00c00\u00c0/\u00cc\u00a8\u00c0')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-23T19:49:25.827043",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.11 - - [23/Aug/2025 19:49:25] code 400, message Bad HTTP/0.9 request type ('\\x16\\x03\\x01\\x05\u00ff\\x01\\x00\\x05\u00fb\\x03\\x03e,\u00eb\u00bb#\\x9d\\x8c\u00e5\u00bf\u00a1Z?\u00fe\u00d0\\x10_\u00e3\u00f62\u00f2\u00bc\u00c2{[\\x19\\x11\\x81\u00fa\u00ed\\x8ddy')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-23T19:49:25.928841",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.11 - - [23/Aug/2025 19:49:25] code 400, message Bad request version (\"\\x82EC\\x83'~\u00c6\\x0eRd\u00c2\\x00*\\x9a\\x9a\\x13\\x02\\x13\\x03\\x13\\x01\u00c0,\u00c0+\u00cc\u00a9\u00c00\u00c0/\u00cc\u00a8\u00c0\")",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-23T19:49:26.030024",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.11 - - [23/Aug/2025 19:49:26] code 400, message Bad request version ('+\u00a3\u00beG\\x1a\u00dc\\x8e\u00e8\\x00*\\x8a\\x8a\\x13\\x02\\x13\\x03\\x13\\x01\u00c0,\u00c0+\u00cc\u00a9\u00c00\u00c0/\u00cc\u00a8\u00c0')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-23T22:51:08.422227",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T22:52:07.111326",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T22:53:05.524613",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T22:54:05.949299",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-23T22:55:07.819177",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 108,
      "filename": "display_manager.py"
    }
  ],
  "error_summary": {
    "ERROR": 264
  },
  "services": {
    "verse_manager": {
      "errors": 0,
      "last_error": null
    },
    "image_generator": {
      "errors": 166,
      "last_error": "2025-08-23T15:52:01.587880"
    },
    "display_manager": {
      "errors": 16,
      "last_error": "2025-08-23T22:55:07.819177"
    },
    "scheduler": {
      "errors": 0,
      "last_error": null
    },
    "service_manager": {
      "errors": 1,
      "last_error": "2025-08-23T14:16:57.936324"
    },
    "web_interface": {
      "errors": 29,
      "last_error": "2025-08-23T15:31:15.857529"
    },
    "voice_control": {
      "errors": 0,
      "last_error": null
    },
    "news_service": {
      "errors": 0,
      "last_error": null
    },
    "weather_service": {
      "errors": 24,
      "last_error": "2025-08-23T14:17:02.224534"
    },
    "other": {
      "errors": 28,
      "last_error": "2025-08-23T19:49:26.030024"
    }
  }
}