{
  "date": "2025-08-30",
  "created_at": "2025-08-30T00:23:09.379697",
  "error_count": 101,
  "errors": [
    {
      "timestamp": "2025-08-30T00:59:12.033852",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:02:11.946965",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.31 - - [30/Aug/2025 01:02:11] code 400, message Bad request version ('\u00b3a\u00fa\\x1b\u00e8.\\x0e+{N?#i\u00c1;\u00e0\\x92\u00e8\u00e6\u00afD\\x9br\u00d4\\x7f\u00e6\u00c3^\u00e2k)V\\x00***\\x13\\x02\\x13\\x03\\x13\\x01\u00c0,\u00c0+\u00cc\u00a9\u00c00\u00c0/\u00cc\u00a8\u00c0')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-30T01:02:12.039676",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.31 - - [30/Aug/2025 01:02:12] code 400, message Bad request version ('\u00f9\\x18\u00f1L\\x1b\u00c7Qg?E\u00a9)5\\x81\u00f4PBlG2\u00ea\\x00*\u00ca\u00ca\\x13\\x02\\x13\\x03\\x13\\x01\u00c0,\u00c0+\u00cc\u00a9\u00c00\u00c0/\u00cc\u00a8\u00c0')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-30T01:02:12.131379",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.31 - - [30/Aug/2025 01:02:12] code 400, message Bad HTTP/0.9 request type ('\\x16\\x03\\x01\\x05\u00ff\\x01\\x00\\x05\u00fb\\x03\\x03\u00a3')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-30T01:02:12.224230",
      "service": "other",
      "logger": "werkzeug",
      "level": "ERROR",
      "message": "192.168.68.31 - - [30/Aug/2025 01:02:12] code 400, message Bad request syntax ('\\x16\\x03\\x01\\x05\u00ff\\x01\\x00\\x05\u00fb\\x03\\x03\\x15\u00aa\\x0e\\x9d\u00b6D\\x8e\\x91\u00aem\u00a4')",
      "function": "_log",
      "line": 97,
      "filename": "_internal.py"
    },
    {
      "timestamp": "2025-08-30T01:04:59.608451",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:11:59.030526",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:17:50.780466",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:22:35.687189",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:27:00.086370",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:30:18.943341",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:36:41.313281",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:39:54.649190",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:43:33.395423",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:56:15.146738",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:57:09.455577",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 210,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:57:09.473764",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 210,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:57:22.282572",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: Timed out waiting for display to respond",
      "function": "display_image",
      "line": 210,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:57:22.299395",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "\ud83d\udea8 Hardware error threshold reached - initiating automatic recovery for gift recipient",
      "function": "display_image",
      "line": 236,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:58:01.876443",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Display update failed: You must setup() the GPIO channel first",
      "function": "display_image",
      "line": 210,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:58:01.888457",
      "service": "display_manager",
      "logger": "display_manager",
      "level": "ERROR",
      "message": "Hardware/GPIO error detected (count: 1/2): You must setup() the GPIO channel first",
      "function": "display_image",
      "line": 227,
      "filename": "display_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:58:11.623921",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T01:58:49.728388",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T02:01:15.202166",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    },
    {
      "timestamp": "2025-08-30T02:02:56.569838",
      "service": "service_manager",
      "logger": "service_manager",
      "level": "ERROR",
      "message": "Voice control auto-initialization failed: name 'enabled' is not defined",
      "function": "run",
      "line": 121,
      "filename": "service_manager.py"
    }
  ],
  "error_summary": {
    "ERROR": 101
  },
  "services": {
    "verse_manager": {
      "errors": 0,
      "last_error": null
    },
    "image_generator": {
      "errors": 0,
      "last_error": null
    },
    "display_manager": {
      "errors": 78,
      "last_error": "2025-08-30T01:58:01.888457"
    },
    "scheduler": {
      "errors": 0,
      "last_error": null
    },
    "service_manager": {
      "errors": 18,
      "last_error": "2025-08-30T02:02:56.569838"
    },
    "web_interface": {
      "errors": 1,
      "last_error": "2025-08-30T00:52:55.824440"
    },
    "voice_control": {
      "errors": 0,
      "last_error": null
    },
    "news_service": {
      "errors": 0,
      "last_error": null
    },
    "weather_service": {
      "errors": 0,
      "last_error": null
    },
    "other": {
      "errors": 4,
      "last_error": "2025-08-30T01:02:12.224230"
    }
  }
}